### ISSUE TITLE
Error when running visualize.py with Pneuma Data 

### ISSUE THREAD

**Issue by ahmedshahnisar** [tud-hri/travia#11]
I tried to run the package with Pneuma data but it ran into some errors. 
The data file I used for it was 20181024_d5_1000_1030.csv, where, the date is 24/10/2018, the drone number is  5 and the time is 10:00 to 10:30. 
As the data from Pneuma is arranged in a single column with ( ; ) as the delimiter.
The **first 4 columns include information about the trajectory like the unique trackID, the type of vehicle, the distance traveled in meters and the average speed of the vehicle in km/h**– **the next 6 columns are then repeated every 6 columns** based on the time frequency. For example, column_5 contains the latitude of the vehicle at time column_10, and column­­­_11 contains the latitude of the vehicle at time column_16. 
But important thing to note is that, the data format is not consistent in the CSV file. 
In my case, the vehicle number 1's data was continued in the second row because the first row became full. 
But the code for Trivia is designed to find the entry as                     
                vehicle = [int(as_list[0]), str(as_list[1]), float(as_list[2]), float(as_list[3])]                                 (pneumadataset.py, ln 94)
So it tries to read the first entry in row 2 which turns out to be a float point and not int

hence the error i encountered is, 

Traceback (most recent call last):
  File "C:\Desktop\Travia\travia-master\visualize.py", line 144, in <module>
    data = PNeumaDataset.load(dataset_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Desktop\Travia\travia-master\dataobjects\pneumadataset.py", line 60, in load
    dataset = PNeumaDataset.read_pneuma_csv(dataset_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Desktop\Travia\travia-master\dataobjects\pneumadataset.py", line 94, in read_pneuma_csv
    vehicle = [int(as_list[0]), str(as_list[1]), float(as_list[2]), float(as_list[3])]
               ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '3.728195'

Now the fix would probably include some check for whether the next row starts with the new vehicle or not and If it does not then the data needs to be aggregated with the first row but the values are for the last 6 columns. 

Uploaded is the ss of csv file, you can see that the 1st vehicle's data continues for a number of rows. 
![Screenshot 2023-11-14 031056](https://github.com/tud-hri/travia/assets/150780255/ce46ccda-ecfc-420a-8f3d-dc47e5ddfca3)

The windows version is Win 11 Home
Python version is 3.12.0 
IDE used is PyCharm Community Edition

**Comment by OlgerSiebinga** [comment]
Hi @ahmedshahnisar,

I've tried to reproduce your error, but I couldn't. I have downloaded the data file from the open-traffic Pneuma website, and for me, it looks like this:

![image](https://github.com/tud-hri/travia/assets/17888242/af9ac508-0641-4fb7-8a0e-da45fbbc96c9)

I can see a new line for every vehicle entry. So I suspect your problem is with Excel, not with the data or TraViA. I've seen other issues before where Excel changes the structure of the *.csv files without being clear about it.

Could you try to download a fresh copy of the file and load it in TraViA **without** opening it in Excel first? If you want to inspect the file before using it, I recommend using [Notepad++](https://notepad-plus-plus.org/) (its a great free and lightweight text editor for files such as *csv). 

Let me know if this worked!

**Comment by ahmedshahnisar** [comment]
Thanks @OlgerSiebinga,

I tried the new editor and it seems to keep the data consistent. 
But after running again, I finally encountered some more errors, 

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\pykalman\utils.py", line 111, in get_params
    args = inspect.getargspec(obj.__init__)[0]
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Desktop\Travia\travia-master\visualize.py", line 144, in <module>
    data = PNeumaDataset.load(dataset_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\Travia\travia-master\dataobjects\pneumadataset.py", line 60, in load
    dataset = PNeumaDataset.read_pneuma_csv(dataset_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\Travia\travia-master\dataobjects\pneumadataset.py", line 126, in read_pneuma_csv
    smooth_pneuma_data(vehicles_df, tracks_total_df, dt.total_seconds())
  File "C:\Users\Desktop\Travia\travia-master\processing\kalmansmoothing.py", line 158, in smooth_pneuma_data
    result_from_smoothing = ukf.smooth(measured_data)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\pykalman\unscented.py", line 1346, in smooth
    self._initialize_parameters()
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\pykalman\unscented.py", line 724, in _initialize_parameters
    arguments = get_params(self)
                ^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\pykalman\utils.py", line 118, in get_params
    raise ValueError("object has no __init__ method")
ValueError: object has no __init__ method

Is it the python version which is causing the problem?
