### ISSUE TITLE
.travia path error when saving pickles

### ISSUE THREAD

**Issue by tomalrussell** [tud-hri/travia#3]
When running `python visualize.py` for the first time, travia fails to create the `~/.travia` folder:
```
Traceback (most recent call last):
  File "visualize.py", line 71, in <module>
    data = NGSimDataset.load(dataset_id)
  File "travia/dataobjects/ngsimdataset.py", line 50, in load
    dataset.save()
  File "travia/dataobjects/ngsimdataset.py", line 41, in save
    save_encrypted_pickle('data/' + self.dataset_id.data_sub_folder + self.dataset_id.data_file_name + '.pkl', self)
  File "travia/processing/encryptiontools.py", line 41, in save_encrypted_pickle
    key = _get_key()
  File "travia/processing/encryptiontools.py", line 29, in _get_key
    os.mkdir(home_folder + '\\.travia\\')
PermissionError: [Errno 13] Permission denied: '/home/username\\.travia\\'
```

Suggested fix: use `os.path.join` to avoid hard-coding OS-dependent path separators.

```diff
 def _get_key():
     home_folder = os.path.expanduser("~")
+    travia_folder = os.path.join(home_folder, '.travia')
+    key_file = os.path.join(travia_folder, '.traffic_data_key')

-    if not os.path.isfile(home_folder + '\\.travia\\.traffic_data_key'):
-        os.mkdir(home_folder + '\\.travia\\')
+    if not os.path.isfile(key_file):
+        os.mkdir(travia_folder)
         new_key = Fernet.generate_key()
-        with open(home_folder + '\\.travia\\.traffic_data_key', 'wb') as file:
+        with open(key_file, 'wb') as file:
             file.write(new_key)
```

**Comment by OlgerSiebinga** [comment]
Thanks for the proposed fix! I've implemented it and changed all other file paths in the code to `os.path` generated paths, just in case. (commit decbc23)
