### ISSUE TITLE
Pneuma image data not found

### ISSUE THREAD

**Issue by tomalrussell** [tud-hri/travia#4]
I've downloaded a CSV for dataset `D181030_T0930_1000_DR1` from https://open-traffic.epfl.ch/index.php/downloads/ 

I can see options for the various CSVs on the pneuma site, but no obvious images or aerial photos (unlike NGSIM).

The data loads and processes okay (with a few warnings) but then fails with this error:

```
Traceback (most recent call last):
  File "visualize.py", line 103, in <module>
    visualize_traffic_data(data, dataset_id, app)
  File "visualize.py", line 33, in visualize_traffic_data
    gui = TrafficVisualizerGui(data)
  File "travia/gui/gui.py", line 53, in __init__
    self.view = WorldView(self, dataset.dataset_id)
  File "travia/gui/worldview.py", line 43, in __init__
    self._load_background(dataset_id)
  File "travia/gui/worldview.py", line 91, in _load_background
    with open(path_to_file + '.tfw', 'r') as map_info_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/pNeuma/images/pneuma.tfw'
```

<details>
<summary>Warnings, in case of interest</summary>

```
WARNING: smoothing for vehicle with ID 28 failed
WARNING: smoothing for vehicle with ID 75 failed
WARNING: smoothing for vehicle with ID 84 failed
WARNING: smoothing for vehicle with ID 86 failed
WARNING: smoothing for vehicle with ID 88 failed
WARNING: smoothing for vehicle with ID 89 failed
WARNING: smoothing for vehicle with ID 90 failed
WARNING: smoothing for vehicle with ID 176 failed
WARNING: smoothing for vehicle with ID 209 failed
WARNING: smoothing for vehicle with ID 338 failed
WARNING: smoothing for vehicle with ID 356 failed
WARNING: smoothing for vehicle with ID 376 failed
WARNING: smoothing for vehicle with ID 380 failed
WARNING: smoothing for vehicle with ID 381 failed
WARNING: smoothing for vehicle with ID 405 failed
WARNING: smoothing for vehicle with ID 475 failed
WARNING: smoothing for vehicle with ID 650 failed
WARNING: smoothing for vehicle with ID 742 failed
```

</details>

Can you point me to an image file to download? Have I missed any instructions in the README or data folder?

**Comment by OlgerSiebinga** [comment]
The pneuma background should have been in the repository but wasn't. I've added it in commit eefae3a
